### ISSUE TITLE
currently broken due to new chromedriver version

### ISSUE THREAD

**Issue by kel-z** [kel-z/UBC-Course-Scout#1]
https://groups.google.com/g/chromedriver-users/c/Z_CaHJTJnLw

**Comment by zpv** [comment]
:'(

**Comment by kel-z** [comment]
radical fix but the issue hasn't been addressed for the past 3 chromedriver releases (v99 - v102) and there are no known solutions currently.

- force selenium to use the last-working browser version by bundling v98 chromedriver and chrome binary with the executable
https://github.com/kel-z/UBC-Course-Scout/commit/8dfc4adcc466565bb35e82b5467fee93c30db0c8
